# Generated by Django 5.2.6 on 2025-09-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projects_created_at_projects_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="roles_required",
            field=models.ManyToManyField(to="projects.rolesrequired"),
        ),
        migrations.AlterField(
            model_name="rolesrequired",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projects"
            ),
        ),
    ]
