# Generated by Django 5.2.6 on 2025-09-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projects_roles_required_alter_rolesrequired_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="roles_required",
        ),
        migrations.AlterField(
            model_name="rolesrequired",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles_required",
                to="projects.projects",
            ),
        ),
    ]
