# Generated by Django 5.2.6 on 2025-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_projects_roles_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolesrequired",
            name="count",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
