# Generated by Django 5.2.6 on 2025-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_rolesrequired_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("approved", "APPROVED"),
                    ("rejected", "REJECTED"),
                    ("invited", "INVITED"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
