# Generated by Django 5.2.6 on 2025-09-24 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammembers",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="projects",
            name="members_required",
        ),
        migrations.AddConstraint(
            model_name="teammembers",
            constraint=models.UniqueConstraint(
                fields=("project", "member"), name="unique_project_member"
            ),
        ),
    ]
